backend:
  name: github
  repo: ngfreyman-jpg/forfriends-catalog
  branch: main
  base_url: https://forfriends-oauth-production.up.railway.app
  auth_endpoint: /auth

site_url: https://ngfreyman-jpg.github.io/forfriends-catalog
display_url: https://ngfreyman-jpg.github.io/forfriends-catalog

# где храним загруженные из админки файлы
media_folder: "images"
# как эти файлы будут доступны на сайте (учитываем имя репозитория)
public_folder: "/forfriends-catalog/images"

publish_mode: editorial_workflow

collections:
  - name: "catalog"
    label: "Каталог"
    files:
      - file: "data/categories.json"
        name: "categories"
        label: "Категории"
        fields:
          - label: "Категории"
            name: "items"
            widget: "list"
            field:
              { label: "Название", name: "title", widget: "string" }

      - file: "data/products.json"
        name: "products"
        label: "Товары"
        fields:
          - label: "Товары"
            name: "items"
            widget: "list"
            fields:
              - { label: "ID", name: "id", widget: "string" }
              - { label: "Название", name: "title", widget: "string" }
              - { label: "Цена", name: "price", widget: "number", value_type: "int", min: 0, step: 1 }
              - { label: "Категория", name: "category", widget: "string" }
              - { label: "Фото", name: "photo", widget: "image", required: false }
              - { label: "Ссылка", name: "link", widget: "string", required: false }
              - { label: "Описание", name: "desc", widget: "text", required: false }
